actions:
  eslint:
    description: eslint
    run: ./node_modules/.bin/eslint --color --max-warnings 0 {files}
    fix: ./node_modules/.bin/eslint --color --max-warnings 0 --fix {files}
    include:
      - "*.js"
      - "*.ts"
      - "*.tsx"
    exclude:
      - ".eslintrc.js"
      - ".prettierrc.js"
  typescript:
    description: tsc-type-checking
    run: ./node_modules/.bin/tsc --noEmit --project tsconfig.json
    include:
      - "content/*.js"
      - "*.ts"
      - "*.tsx"
  stylelint:
    run: ./node_modules/.bin/stylelint {files}
    fix: ./node_modules/.bin/stylelint {files} --fix
    include:
      - "*.css"
      - "*.less"

shortcuts:
  lint:
    flags:
      - include-unstaged
      - include-untracked
  "lint:all":
    extends: lint
    flags: use-tracked-files
  fix:
    extends: lint
    flags: fix
  "fix:all":
    extends: fix
    flags: use-tracked-files
