status = [
  "ci/circleci: lint",
  "ci/circleci: test",
  "ci/circleci: build"
]
# Avoid including verbose details from PR bodies
cut_body_after = "<details>"
block_labels = ["bors-dont-merge"]
delete_merged_branches = true
