coverage:
  status:
    default_rules:
      patch: off
      target: auto
      threshold: 0%
      base: auto
      # don't fail CI builds for coverage
      informational: true

comment:
  layout: "diff,flags,tree"
  require_changes: true
